name: cmmrt_app
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - optuna>=2.8.0
  - catboost>=0.25.1
  - pytorch>=1.7.1
  - pandas=1.4.4
  - xgboost=1.3.3
  - gdown>=3.13.0
  - gpytorch>=1.4.2
  - lightgbm>=3.2.1
  - scikit-learn>=0.24.2
  - matplotlib>=3.3.3
